# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

variables:
- group: Keystore

steps:

- task: DownloadSecureFile@1
  name: keyStore # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
  inputs:
    secureFile: upload.keystore

- script: |
    echo Copy file to android/app directory
    cp $(keyStore.secureFilePath) $(Build.Repository.LocalPath)/android/app/upload.keystore
  displayName: 'Install Keystore'

- script: |
    flutter -v build appbundle --target-platform android-arm,android-arm64
  displayName: 'Make App Bundle'
  env:
    APPCENTER_KEYSTORE_PASSWORD: $(APPCENTER_KEYSTORE_PASSWORD)
    APPCENTER_KEY_ALIAS: $(APPCENTER_KEY_ALIAS)
    APPCENTER_KEY_PASSWORD: $(APPCENTER_KEY_PASSWORD)
    APPCENTER_BUILD_ID: $(Build.BuildId)

- script: |
    echo Clean keystore
    rm $(Build.Repository.LocalPath)/android/app/upload.keystore
  displayName: 'Clean Keystore'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Bundle'
  inputs:
    PathtoPublish: $(Build.Repository.LocalPath)/build/app/outputs/bundle/release


