# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

variables:
- group: Keystore

steps:

- task: DownloadSecureFile@1
  name: keyStore # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
  inputs:
    secureFile: upload.keystore

- task: DownloadSecureFile@1
  name: appjson # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
  inputs:
    secureFile: bitit-appcenter-api-4906382300011793390-749671-67207996945b.json

- script: |
    echo Copy file to android/app directory
    cp $(keyStore.secureFilePath) $(Build.Repository.LocalPath)/android/app/upload.keystore
  displayName: 'Install Keystore'

- script: |
    flutter -v build appbundle --target-platform android-arm,android-arm64
  displayName: 'Make App Bundle'
  env:
    APPCENTER_KEYSTORE_PASSWORD: $(APPCENTER_KEYSTORE_PASSWORD)
    APPCENTER_KEY_ALIAS: $(APPCENTER_KEY_ALIAS)
    APPCENTER_KEY_PASSWORD: $(APPCENTER_KEY_PASSWORD)
    APPCENTER_BUILD_ID: $(Build.BuildId)


- script: |
    fastlane supply  --aab $(Build.Repository.LocalPath)/build/app/outputs/bundle/release/app-release.aab --track internal  --json_key $(appjson.secureFilePath) --release_status draft --package_name fi.bitit.flutterdemo --rollout 1
    echo fastlane upload_to_play_store_internal_app_sharing --aab $(Build.Repository.LocalPath)/build/app/outputs/bundle/release/app-release.aab --json_key $(appjson.secureFilePath) --package_name fi.bitit.flutterdemo
  displayName: 'Upload to internal app'

- script: |
    echo Remove securefiles
    rm $(Build.Repository.LocalPath)/android/app/upload.keystore
    rm $(appjson.secureFilePath)
  displayName: 'Remove securefiles'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Bundle'
  inputs:
    PathtoPublish: $(Build.Repository.LocalPath)/build/app/outputs/bundle/release


